config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  root 'tweets#index'
  resources :tweets do
   resources :comments,only:[:create]
  end
  resources :users ,only:[:show]
end


# get 'tweets/new' => 'tweets#new'
# post 'tweets' => 'tweets#create'
# delete 'tweets/:id' => 'tweets#destroy'
# get 'tweets/:id' => 'tweets#edit'
# get 'tweets/show' => 'tweets#show'
# patch 'tweets/:id' => 'tweets#update'
# get 'users/:id' => 'tweets#show'
# post 'tweets/:tweet_id/comments' => 'comments#create'

#ここでルーティングを組んでいる。devie_for :usersで、ユーザーのログイン周りのルーティングを全て組んでいる。また、最初のページでindex画面を表示させるように設定し、tweetsコントローラに対しリソースを組んでいる。さらに、どのtweetのcommentかを明示化するために、ネストさせており、クリエイトアクションのみ実行可能にしている。
#その次に、usersコントローラのshowアクションのみルーティングを組んでいる。

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
#ルイールコントローラーにアプリケーションを継承する

  # before_action :move_to_index, except: [:index,:show]
  #全てのアクションの実行前にインデックスページに飛ぶ。ただし、インデックスページと詳細ページは除く

  def index
     @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    #ツイートモデルを降順に５件のみ表示させる左辺を、ビューファイルで使用したい@tweetsに入れる そこで定義

  end

  def new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
  end
   #ツイートモデルのインスタンスの新規作成をし、保存するメソッド過程。パラムズに:image,:textを入れている。また、paramsに入れる必要のないuser_idは、current_userメソッドを使って自動で入れている

  def destroy
    tweet= Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    #投稿を削除する。キーとしての:idがバリューで任意のツイートidが入り、ツイートをしたユーザーのid(アソシエーションを組んでいる)と現在ログイン中のユーザーidが等しければ、ツイートは削除される。
    #current_user.idで現在ログイン中のユーザーのusersテーブルのidカラムの情報を引き出している
  end

  def edit
    @tweet = Tweet.find(params[:id])
    #投稿を編集し、ビューファイルへ投げるため、＠tweetへ代入する。
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
       #ツイートを上書きするための変数tweetを定義。その変数tweetのuser_idと現在ログイン中のユーザーidが等しければ、変数tweetはtweet_paramsの:name,:image,:textを上書きする。
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    #詳細画面をビューファイルに反映させるためのキーとしての:id・バリューで任意のツイートidが入る@tweetを定義。
    #上記定義した@twseetには１：多の関係でcommentsがつくため、アソシエーションを組んだ上で、n+1問題をincludesで解決している。
  end

  private
  def tweet_params
    params.permit( :image, :text)
     ##外部から呼び出されないメソッドである。paramsの中身には、:image.:textのみしか通過できないということを定義
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
    #ユーザーがサインインしていない限り、インデックス画面に遷移する。
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

<!--

6 インデックスページから詳細ページへのリンクを書いている。
8 ユーザーがサインインをしている状態かつ、現在ログイン中のユーザーidがツイートのユーザーidと等しい場合、編集と削除ボタンを表示させる仕組みになっている
10 /tweets/#{tweet.id}/editというページへの遷移ボタンを描く仕組み。メソッドはgetでページを表示させる
13 /tweets/#{tweet.id}というページに遷移させるためのツイートを削除するボタン。deleteメソッドで削除している。
18 simple_formatでtweetのtextの改行を適用させている。
20 /users/tweet.user_idページへの遷移を促している。
21 投稿者と、改行をし、アソシエーションを組んでいるため、tweetとユーザーは1:1であり、ツイートをしたユーザーのニックネームを表示させている。

  -->

app/views/tweets/create.html.erb
 <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
  <div class="contents row">
    <%=form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
      <h3>
        編集する
      </h3>
      <input placeholder="Image Url" type="text" name="image" value=<%= @tweet.image %> autofocus="true">
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>


</div>

app/views/tweets/index.html.erb
<div class="contents row">

  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

<!--eachメソッドを使い、tweetを繰り返して表示させて設定を１度で済むようにしている。
renderメソッドで、部分テンプレートへの遷移を促し、partialで、移動テンプレートを'tweet'と明示的にしている。
localsを使用し、右辺tweetの文字列が代入された左辺tweetを部分テンプレート内で使用できる。
また、ビューファイルで記載したように、ページネーションを実行するため、@tweetsでページネーションを有効化している。 -->

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweets', method: :post) do %>
        <h3>
        投稿する
      </h3>
      <input placeholder="Image Url" type="text" name="image">
      <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
    <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- ユーザーがサインインしていて、かつ現在ログイン中のユーザーのidがツイートのユーザーidと一致して入れば、編集と削除ボタンが詳細ページで現れる。サインインしていない状態の場合、ボタンは表示されない。
16 simple_formatでtweetのtextの改行を適用させている。
18 /users/tweet.user_idページへの遷移を促している。
19 投稿者と、改行をし、アソシエーションを組んでいるため、tweetとユーザーは1:1であり、ツイートをしたユーザーのニックネームを表示させている。
25 ログインしているユーザーであれば、showページに遷移した際、コメントを投稿することができる。-
27 text属性で、何もない状態だと薄く、”コメントしてください”の文字が出るようになっている。
33 commentsコントローラーと連動し、もし@comment = Comment.create(text: params[:text], tweet_id: params[:tweet_id], user_id: current_user.id)このように作られたコメントが存在する場合、コメント履歴が以下表示される仕様である
34 eachメソッドでコメントを繰り返し表示している
36 1つのcommentに対しuserは1:1なのでコメントをしたユーザーのニックネームを押すと、/users/#{comment.user_id}とあり、コメントをしたユーザーの情報が一覧で表示される。
37 comment.textで変数.カラム名で、DBからcommentテーブルのtextカラムの情報を引き出すことができる。

->

app/views/tweets/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>